//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Owner\\Desktop\\mc\\Minecraft.exe")]
        public string Minecraft {
            get {
                return ((string)(this["Minecraft"]));
            }
            set {
                this["Minecraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Owner\\Desktop\\mc\\server")]
        public string MinecraftServerPath {
            get {
                return ((string)(this["MinecraftServerPath"]));
            }
            set {
                this["MinecraftServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Owner\\Dropbox")]
        public string MinecraftServerBackupPath {
            get {
                return ((string)(this["MinecraftServerBackupPath"]));
            }
            set {
                this["MinecraftServerBackupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Owner\\Desktop\\mc\\B NBTExplorer\\NBTExplorer.exe")]
        public string NbtExplorer {
            get {
                return ((string)(this["NbtExplorer"]));
            }
            set {
                this["NbtExplorer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Owner\\Desktop\\installs\\MCEdit-stable33-64bit-win32\\mcedit\\MCEdit-64bit\\m" +
            "cedit.bat")]
        public string MCEdit {
            get {
                return ((string)(this["MCEdit"]));
            }
            set {
                this["MCEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Owner\\Desktop\\mc\\bMinecraftChat\\PacketPasser.exe")]
        public string bMinecraftChat {
            get {
                return ((string)(this["bMinecraftChat"]));
            }
            set {
                this["bMinecraftChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>CraftBukkit,http://www.google.com/reader/view/feed%2Fhttp%3A%2F%2Fdl.bukkit.org%2Fdownloads%2Fcraftbukkit%2Ffeeds%2Flatest-rb.rss</string>
  <string>Sign Tutorial,http://ess.khhq.net/wiki/Sign_Tutorial</string>
  <string>McMmo,http://mcmmo.wikia.com/wiki/McMMO_Wiki</string>
  <string>Multiverse 2,https://github.com/Multiverse/Multiverse-Core/wiki</string>
  <string>PermissionsEx,https://github.com/t3hk0d3/PermissionsEx/wiki</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Links {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Links"]));
            }
            set {
                this["Links"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Admin</string>\r\n  <string>Maslow</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MinecraftAliases {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MinecraftAliases"]));
            }
            set {
                this["MinecraftAliases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%appdata%\\.minecraft\\bin")]
        public string MinecraftBinPath {
            get {
                return ((string)(this["MinecraftBinPath"]));
            }
            set {
                this["MinecraftBinPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Java\\jre6\\bin\\java.exe")]
        public string Java {
            get {
                return ((string)(this["Java"]));
            }
            set {
                this["Java"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%appdata%\\.minecraft\\")]
        public string MinecraftClientPath {
            get {
                return ((string)(this["MinecraftClientPath"]));
            }
            set {
                this["MinecraftClientPath"] = value;
            }
        }
    }
}
